# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accept.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from select import select
from PyQt5 import QtCore, QtGui, QtWidgets
import pyautogui
from keyboard import is_pressed
from time import sleep

def main():
    sleep(5)
    while True:
        sleep(0.5)
        pyautogui.click(679,533)
        if is_pressed('q'):
            break

class Ui_Accept(object):
    def setupUi(self, Accept):
        Accept.setObjectName("Accept")
        Accept.resize(631, 380)
        Accept.setMinimumSize(QtCore.QSize(631, 380))
        Accept.setMaximumSize(QtCore.QSize(631, 380))
        self.centralwidget = QtWidgets.QWidget(Accept)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(-200, -230, 300, 300))
        self.frame_2.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(720, 460, 300, 300))
        self.frame_3.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(880, -20, 300, 300))
        self.frame_4.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(-280, 470, 300, 300))
        self.frame_5.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(220, 90, 200, 200))
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color:white;\n"
"    border: 5px solid rgb(48, 189, 242);;\n"
"    border-radius:100px;\n"
"    font: 30pt \"Permanent Marker\";\n"
"    color:  rgb(200, 155, 60);\n"
"    transition: 1s;\n"
" }\n"
"\n"
" QPushButton#pushButton:hover {\n"
"    border-radius:100px;\n"
"    border: 5px solid rgb(40, 102, 241);\n"
" }\n"
"\n"
" QPushButton#pushButton:pressed {\n"
"    color: rgb(40, 102, 241);\n"
" }")
        self.pushButton.setObjectName("pushButton")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(530, 290, 300, 300))
        self.frame_6.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(620, -100, 300, 300))
        self.frame_8.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(-280, 230, 300, 300))
        self.frame_7.setStyleSheet("background-color: rgb(48, 189, 242);\n"
"border-radius: 150px")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout.addWidget(self.frame)
        Accept.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(Accept)
        QtCore.QMetaObject.connectSlotsByName(Accept)




        self.pushButton.clicked.connect(main)





    def retranslateUi(self, Accept):
        _translate = QtCore.QCoreApplication.translate
        Accept.setWindowTitle(_translate("Accept", "MainWindow"))
        self.pushButton.setText(_translate("Accept", "Aceitar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Accept = QtWidgets.QMainWindow()
    ui = Ui_Accept()
    ui.setupUi(Accept)
    Accept.show()
    sys.exit(app.exec_())
